apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-user
  labels:
    app: netflix-user
  namespace: netflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-user
  template:
    metadata:
      labels:
        app: netflix-user
    spec:
      containers:
      - name: netflix-user
      image: 471524526724.dkr.ecr.us-east-1.amazonaws.com/netflix-user:latest
      ports:
      - containerPort: 3000